version: "2"
run:
  build-tags:
    - e2e
linters:
  default: none
  enable:
    - bodyclose # checks HTTP response body is closed
    - copyloopvar # detects loop variable copies (Go 1.22+)
    - dogsled # finds too many blank identifiers (x, _, _, _ := f())
    - dupl # detects duplicate code fragments
    - errcheck # checks for unchecked errors
    - errorlint # checks for proper error wrapping and comparison
    - goconst # finds repeated strings replaceable by constants
    - gocritic # catches common pitfalls: nil checks, type assertions, slicing
    - gocyclo # checks cyclomatic complexity
    - goprintffuncname # checks printf-like funcs end with 'f'
    - gosec # inspects source code for security problems
    - govet # catches format-string mismatches, struct tag errors, lock copies
    - ineffassign # detects unused assignments
    - misspell # finds common spelling mistakes
    - modernize # suggests modern Go idioms and stdlib usage
    - nolintlint # enforces well-formed nolint directives
    - revive # enforces naming, imports, error returns, and style rules
    - staticcheck # finds bugs, deprecated APIs, and unnecessary code
    - testifylint # correctness checks for testify usage
    - unconvert # removes unnecessary type conversions
    - unparam # reports unused function parameters
    - unused # checks for unused code
    - whitespace # checks for unnecessary newlines
  exclusions:
    generated: lax # exclude generated files
    presets:
      # suppress "exported X should have comment" — not all exports are documented
      - comments
    rules:
      # test files: relax duplicate detection and unused params
      - linters:
          - dupl
          - unparam
        path: _test\.go
      - linters:
          - revive
        path: _test\.go
        text: unused-parameter
      # test files: unchecked Close/Remove in deferred cleanup
      - linters:
          - errcheck
        path: _test\.go|tests/
        text: "Close|Remove"
      # var-naming: packages that intentionally shadow stdlib names
      - linters:
          - revive
        text: "var-naming: avoid package names that conflict with Go standard library"
        path: interceptor/metrics/|operator/controllers/http/|pkg/build/|pkg/http/|pkg/net/
      # var-naming: util packages with meaningful names
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: pkg/util/|operator/controllers/util/|tests/utils/
      # revive: dot imports are standard for ginkgo/gomega
      - linters:
          - revive
        text: "dot-imports"
        path: _test\.go
      # gosec: relaxed TLS settings in tests
      - linters:
          - gosec
        text: "G402"
        path: _test\.go
      # gosec: ignore impossible integer overflow on port/replica conversions
      - linters:
          - gosec
        text: "G109|G115"
        path: _test\.go|tests/|pkg/k8s/fake_
      # gosec: weak RNG is fine for test data
      - linters:
          - gosec
        text: "G404"
        path: _test\.go|tests/
      # gosec: test helpers invoke subprocesses with known inputs
      - linters:
          - gosec
        text: "G204|G702"
        path: tests/
      # gosec: test HTTP requests target local test servers, not user-controlled URLs
      - linters:
          - gosec
        text: "G704"
        path: _test\.go
formatters:
  enable:
    - gci # import grouping and ordering
    - gofumpt # stricter superset of gofmt
    - goimports # adds/removes imports, formats code
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
  exclusions:
    generated: lax # exclude generated files
    paths:
      # gci would strip kubebuilder scaffold markers from import blocks
      - operator/controllers/http/suite_test.go
      - operator/main.go
